version: '3'
services:
  web:
    image: "invoicer:latest"
    ports:
        - "8080:8112"
    volumes:
        - "../instance:/usr/src/app/instance"
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
        - "8081:80"
