"""Adding `rehash_password` column to `users`

Revision ID: 64f6a347f887
Revises: 661fe2c47ddc
Create Date: 2018-04-05 09:11:42.291000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f6a347f887'
down_revision = '661fe2c47ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rehash_password', sa.Boolean(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    '''Remove `rehash_password` from `users`'''
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column('rehash_password')

