"""empty message

Revision ID: 661fe2c47ddc
Revises: f9d9b163eaaa
Create Date: 2018-03-29 10:56:09.386000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661fe2c47ddc'
down_revision = 'f9d9b163eaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bs4_themes')
    op.drop_table('w3_themes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'w3_themes',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('theme', sa.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'bs4_themes',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('theme', sa.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
